[project]
name = "ai-sample"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain[google-genai]>=0.3.27",
    "mypy>=1.11",
    "ruff>=0.12.10",
]
